### ISSUE TITLE
About using the model.

### ISSUE THREAD

**Issue by Cc-Hy** [dg-enlens/banet-depth-prediction#1]
Hello, 
I wanna use this depth prediction model to  construct my model on KITTI 3d detection task, specifically, i'd like it to generate a 4 times downsampled depth map with respect to the raw KITTI image(e.g. for an image of size 1242 * 375,  i want to get a depth map of size 311 * 94), so i could simply use your pre-trained model by using
`... --height 94 --width 311`
Is that right? 
Or is it better that i train a new model using 
`... --train --height 94 --width 311`

**Comment by dg-enlens** [comment]
Hi Hy,

Unfortunately, the output image size is tied with the model. If you try to load our pre-trained model for a resolution different than `--height 128 --width 416`, you will probably get an error. You'd better redo a training at the desired resolution.

Also, please note that the `--width` and `--height` values must be multiple of **32**. Your desired resolution of [311 x 94] won't work. You should probably select something like [320 x 96] instead.

Thanks
