### ISSUE TITLE
How to reproduce the results on kitti dataset

### ISSUE THREAD

**Issue by RobinhoodKi** [dg-enlens/banet-depth-prediction#2]
Hi guys, great work ! Can you release the code about reproducing the results on kitti datasets ?

**Comment by dg-enlens** [comment]
Hi RobinhoodKi,

If you want to reproduce training on the Kitti datasets, you need to:

- Download the [Kitti dataset for depth prediction](http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction) and download corresponding [raw videos](http://www.cvlibs.net/datasets/kitti/raw_data.php). The depth prediction dataset should already be split into a train and a validation set.
- Create two CSV files `train.csv` and `val.csv` pointing to the training and validation images / depth-maps. Each CSV must have two columns `raw_path, depth_path` and each row respectively provides the full paths to RGB images and depth-map images. Examples of CSV files can be found in the samples directory of the repository.
- Training is launched with the following command:

```bash
python3 main.py --train 1 --height 192 --width 416 --train_csv train.csv --val_csv val.csv
```

- Evaluation of the model can be done with the `--inference validation` option:

```bash
python3 main.py --inference validation --model model.pt --height 192 --width 256 --val_csv val.csv
```

I hope this helps.
