### ISSUE TITLE
Prediction's meaning

### ISSUE THREAD

**Issue by stunback** [dg-enlens/banet-depth-prediction#3]
Hello, I'm interested in your paper BANet, but I'm not sure about the meaning of the model output. 

Does the prediction mean absolute depth or relative depth? Is it in meters?

**Comment by dg-enlens** [comment]
Hi stunback,

The prediction provides a float matrix of the same size as the input image, in which each pixel value is the estimated distance of that pixel to the camera center in meters. So if the predicted value for a pixel in your image is `12.4`, it means that this pixel is estimated to be located at 12,4 meters from the camera center.

Feel free to let me know if this is not clear.

Thanks
